[workspace]
authors = ["bethac07 <bcimini@broadinstitute.org>"]
channels = ["conda-forge"]
name = "cellpose3"
platforms = ["osx-arm64", "linux-64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.*"
numpy = "<2"

[pypi-dependencies]
cellpose = { version = "<4", extras = ["all"] }
