[workspace]
authors = ["bethac07 <bcimini@broadinstitute.org>"]
channels = ["conda-forge"]
name = "microsam"
platforms = ["osx-arm64", "win-64", "osx-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
micro_sam = ">=1.7.0,<2"
